placeSnowInBlock = false
placeSnowInBlockNaturally = false
snowGravity = true
snowAlwaysReplaceable = true
snowAccumulationDuringSnowstorm = false
snowAccumulationDuringSnowfall = false
snowAccumulationMaxLayers = 8
thinnerBoundingBox = true
snowMakingIce = true
snowNeverMelt = false
snowAndIceMeltInWarmBiomes = true
snowNaturalMelt = true
snowReduceFallDamage = true
replaceWorldFeature = false
sustainGrassIfLayerMoreThanOne = true
retainOriginalBlocks = false
sneakSnowball = false
mobSpawningMaxLayers = 8

[integration]
accumulationWinterOnly = false

[debug]
weatherTickSlowness = 16
mobSpawningCommand = false
